/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

/**
 *
 * @author silmathoron
 */
public class MainFrame extends javax.swing.JFrame {

    private boolean playing;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        fieldPanel.setParent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statsPanel = new javax.swing.JPanel();
        nodesNumberLabel = new javax.swing.JLabel();
        nodesNumber = new javax.swing.JLabel();
        linksNumberLabel = new javax.swing.JLabel();
        linksNumber = new javax.swing.JLabel();
        fieldPanel = new ihm.FieldPanel();
        buttonsPanel = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
        playPauseToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nodesNumberLabel.setText("Nodes :");
        statsPanel.add(nodesNumberLabel);

        nodesNumber.setText("0");
        statsPanel.add(nodesNumber);

        linksNumberLabel.setText("Links :");
        statsPanel.add(linksNumberLabel);

        linksNumber.setText("0");
        statsPanel.add(linksNumber);

        getContentPane().add(statsPanel, java.awt.BorderLayout.PAGE_START);

        fieldPanel.setBackground(new java.awt.Color(10, 10, 10));

        javax.swing.GroupLayout fieldPanelLayout = new javax.swing.GroupLayout(fieldPanel);
        fieldPanel.setLayout(fieldPanelLayout);
        fieldPanelLayout.setHorizontalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        fieldPanelLayout.setVerticalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        getContentPane().add(fieldPanel, java.awt.BorderLayout.CENTER);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(resetButton);

        playPauseToggle.setText("Play");
        playPauseToggle.setToolTipText("");
        playPauseToggle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                playPauseToggleItemStateChanged(evt);
            }
        });
        buttonsPanel.add(playPauseToggle);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        fieldPanel.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void playPauseToggleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_playPauseToggleItemStateChanged
        if (playing) {
            playing = false;
            fieldPanel.stop();
            playPauseToggle.setText("Play");
        } else {
            playing = true;
            fieldPanel.run();
            playPauseToggle.setText("Pause");
        }
    }//GEN-LAST:event_playPauseToggleItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private ihm.FieldPanel fieldPanel;
    private javax.swing.JLabel linksNumber;
    private javax.swing.JLabel linksNumberLabel;
    private javax.swing.JLabel nodesNumber;
    private javax.swing.JLabel nodesNumberLabel;
    private javax.swing.JToggleButton playPauseToggle;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel statsPanel;
    // End of variables declaration//GEN-END:variables

    void updateStats(int nodes, int links) {
        nodesNumber.setText(""+nodes);
        linksNumber.setText(""+links);
        repaint();
    }
}
